### ISSUE TITLE
[Ruby: turbine examples] Up to date sample ruby app

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-examples#3]
## Context 

As customers begin testing out Ruby, they need a sample app to build an app against.

## Acceptance 

- [x] Ensure the [template ruby example](https://github.com/meroxa/turbine-core/tree/main/lib/ruby/turbine_rb/lib/templates/app) is up to date with [turbine-examples](https://github.com/meroxa/turbine-examples/tree/main/ruby/simple)
    - [x] Has an example for app with function
    - [x] Has an example for app with secrets
    - [x] Has an example for app with connector configs
- [ ] Make repo public

**Comment by janelletavares** [comment]
i just noticed that this app doesn't have any automated testing, which we added to the other examples as a champagne project.  i was just thinking about it because i believe the automation only runs on a PR and not if the apps become outdated. we'll never be alerted if they break... not ideal.
